spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pizza?useSSL=false&serverTimezone=GMT
    username: root
    password: 123456

logging:
  path: ./log
  level:
    root: warn

server:
  port: 8082
  servlet:
    session:
      timeout: 600s